[package]
name = "ttyinv-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "ttyinv"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
serde_json.workspace = true
serde_yaml.workspace = true
ttyinv-core = { version = "0.1.0", path = "../../crates/ttyinv-core" }
